apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller-sre
  namespace: sre
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager-sre
  namespace: sre
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-sre-binding
  namespace: sre
subjects:
- kind: ServiceAccount
  name: tiller-sre
  namespace: sre
roleRef:
  kind: Role
  name: tiller-manager-sre
  apiGroup: rbac.authorization.k8s.io