apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller-dev
  namespace: dev
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-manager-dev
  namespace: dev
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tiller-dev-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: tiller-dev
  namespace: dev
roleRef:
  kind: Role
  name: tiller-manager-dev
  apiGroup: rbac.authorization.k8s.io